### ISSUE TITLE
Cannot slice image objects; consider using img.slicer[slice] to generate a sliced image (see documentation for caveats) or slicing image array data with img.dataobj[slice] or img.get_fdata()[slice]

### ISSUE THREAD

**Issue by DrKrabs** [StanfordMIMI/Comp2Comp#107]
Hi. I'm currently using the the muscle_adipose_tissue pipeline and it works perfectly.
However, I run into some issues when trying to use the spine_muscle_adipose_tissue and liver_spleen_pancreas pipelines, they all give the same type error:
```
force_separate_z: None interpolation order: 0
Traceback (most recent call last):
  File ".../.Trash/Comp2Comp/comp2comp/spine/spine.py", line 135, in spine_seg
    img, seg = nnUNet_predict_image(
  File "....../lib/python3.9/site-packages/nibabel/spatialimages.py", line 645, in __getitem__
    raise TypeError(
TypeError: Cannot slice image objects; consider using `img.slicer[slice]` to generate a sliced image (see documentation for caveats) or slicing image array data with `img.dataobj[slice]` or `img.get_fdata()[slice]`
```
Are there any specific modifications needed for the DICOM files to run these pipelines?

**Comment by DrKrabs** [comment]
DICOM series likes this?  
<img width="728" alt="Screenshot 2023-06-09 at 21 37 27" src="https://github.com/StanfordMIMI/Comp2Comp/assets/124430308/2915a682-aa04-4d82-a86c-75b8c8e92ea6">
Or a whole study with multiple series like this?
<img width="729" alt="Screenshot 2023-06-09 at 21 45 10" src="https://github.com/StanfordMIMI/Comp2Comp/assets/124430308/550ab955-894a-40a5-bae0-032ead340e7f">
Still the same error.
